#!/usr/bin/env node
// Regenerates src/prices.generated.ts from a machine-readable price database.
//
// Primary source is LiteLLM's community-maintained price table, which tracks
// official vendor prices for Anthropic / OpenAI / Google models within hours
// of changes. Scraping the vendor pricing pages directly is deliberately
// avoided: they are JS-rendered and change layout without notice.
//
// Safety rules:
//   - never writes unless every validation passes (see `validate` below)
//   - keys must be idempotent under the same normalization the runtime uses,
//     otherwise generated keys would drift apart from src/pricing.ts
//   - aborts (exit 1, no write) when the payload looks broken
//
// Run manually:  node .github/scripts/update-prices.mjs
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import * as path from 'node:path';

const LITELLM_URL =
  'https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT_FILE = path.join(root, 'src', 'prices.generated.ts');

/** Model families bundled in agentstats; everything else is skipped. */
const FAMILIES = /^(claude|gpt|gemini|codex-mini|o1|o3|o4)(-|$)/;

// Keep in exact sync with normalizeModel() in src/pricing.ts — the runtime
// looks models up with that function, so generated keys must already be in
// normalized form. A test asserts idempotence to catch drift.
function normalizeModel(raw) {
  let m = String(raw).toLowerCase().trim();
  const slash = m.lastIndexOf('/');
  if (slash >= 0) m = m.slice(slash + 1);
  const dot = m.lastIndexOf('.');
  if (dot >= 0 && /^(claude|gpt|gemini|o\d|codex)/.test(m.slice(dot + 1))) {
    m = m.slice(dot + 1);
  }
  m = m.replace(/:[^:]*$/, '');
  m = m.replace(/-\d{8}$/, '');
  m = m.replace(/\./g, '-');
  return m;
}

function num(v) {
  return typeof v === 'number' && Number.isFinite(v) && v >= 0 ? v : null;
}

const r6 = (x) => Math.round(x * 1e6) / 1e6;

async function main() {
  const res = await fetch(LITELLM_URL);
  if (!res.ok) throw new Error(`fetch failed: HTTP ${res.status} for ${LITELLM_URL}`);
  const db = await res.json();
  if (!db || typeof db !== 'object' || Array.isArray(db)) {
    throw new Error('unexpected payload: expected a JSON object of models');
  }

  // collect candidates per normalized key (provider variants + dated snapshots collide)
  const candidates = new Map();
  for (const [rawId, info] of Object.entries(db)) {
    const key = normalizeModel(rawId);
    if (!FAMILIES.test(key)) continue;
    const input = num(info?.input_cost_per_token);
    const output = num(info?.output_cost_per_token);
    if (input === null || output === null) continue;
    const cached = num(info?.cache_read_input_token_cost);
    const list = candidates.get(key) ?? [];
    list.push({ rawId, input, output, cached, exact: rawId === key });
    candidates.set(key, list);
  }

  const table = {};
  for (const [key, list] of candidates) {
    list.sort(
      (a, b) =>
        Number(b.exact) - Number(a.exact) ||
        Number(b.cached !== null) - Number(a.cached !== null) ||
        a.rawId.localeCompare(b.rawId)
    );
    const w = list[0];
    table[key] = {
      input: r6(w.input * 1e6),
      ...(w.cached !== null ? { cachedInput: r6(w.cached * 1e6) } : {}),
      output: r6(w.output * 1e6),
    };
  }

  validate(table);

  const keys = Object.keys(table).sort();
  const fetchedAt = new Date().toISOString();
  const body = [
    '// AUTO-GENERATED by .github/scripts/update-prices.mjs - DO NOT EDIT BY HAND.',
    `// Source: ${LITELLM_URL}`,
    `// Fetched: ${fetchedAt} - ${keys.length} models. Prices are USD per 1M tokens.`,
    '// To pin or add a price, use MANUAL_PRICES in src/pricing.ts (wins over this file)',
    '// or pricingOverrides in ~/.agentstats/config.json (wins over everything).',
    "import type { ModelPrice } from './types.js';",
    '',
    'export const GENERATED_PRICES: Record<string, ModelPrice> = {',
    ...keys.map((k) => {
      const p = table[k];
      const cached = p.cachedInput !== undefined ? `cachedInput: ${p.cachedInput}, ` : '';
      return `  '${k}': { input: ${p.input}, ${cached}output: ${p.output} },`;
    }),
    '};',
    '',
  ];

  let added = keys.length;
  let changed = 0;
  let removed = 0;
  if (existsSync(OUT_FILE)) {
    const prev = readFileSync(OUT_FILE, 'utf8');
    const prevTable = parsePrevTable(prev);
    added = keys.filter((k) => !(k in prevTable)).length;
    changed = keys.filter((k) => k in prevTable && JSON.stringify(prevTable[k]) !== JSON.stringify(table[k])).length;
    removed = Object.keys(prevTable).filter((k) => !(k in table)).length;
  }

  writeFileSync(OUT_FILE, body.join('\n'));
  console.log(`updated src/prices.generated.ts: ${keys.length} models (+${added} new, ~${changed} changed, -${removed} gone), fetched ${fetchedAt}`);
}

function parsePrevTable(text) {
  const match = text.match(/export const GENERATED_PRICES[^=]*= \{([\s\S]*)\};/);
  if (!match) return {};
  const table = {};
  for (const m of match[1].matchAll(/'([^']+)': \{([^}]*)\}/g)) {
    const entry = {};
    for (const field of m[2].matchAll(/(input|cachedInput|output): ([0-9.eE+-]+)/g)) {
      entry[field[1]] = Number(field[2]);
    }
    if (entry.input !== undefined && entry.output !== undefined) table[m[1]] = entry;
  }
  return table;
}

function validate(table) {
  const keys = Object.keys(table);
  const fail = (msg) => {
    throw new Error(`validation failed, NOT writing: ${msg}`);
  };
  if (keys.length < 40) fail(`only ${keys.length} models matched the known families`);
  for (const family of ['claude-', 'gpt-', 'gemini-']) {
    if (!keys.some((k) => k.startsWith(family))) fail(`no models found for family '${family}'`);
  }
  for (const k of keys) {
    if (normalizeModel(k) !== k) fail(`key '${k}' is not in normalized form (normalization drift?)`);
    const p = table[k];
    if (![p.input, p.output].every((v) => Number.isFinite(v) && v >= 0) ||
        (p.cachedInput !== undefined && !(Number.isFinite(p.cachedInput) && p.cachedInput >= 0))) {
      fail(`model '${k}' has a non-finite or negative price`);
    }
  }
  // a fetched table that drops >30% of previously known models is suspicious
  if (existsSync(OUT_FILE)) {
    const prevKeys = Object.keys(parsePrevTable(readFileSync(OUT_FILE, 'utf8')));
    if (prevKeys.length > 0) {
      const gone = prevKeys.filter((k) => !(k in table));
      if (gone.length > prevKeys.length * 0.3) {
        fail(`${gone.length}/${prevKeys.length} previously known models disappeared from the source`);
      }
    }
  }
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
